export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const LESS_QUANTITY = 'LESS_QUANTITY';

export const ADD_WISHLIST = 'ADD_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';